name: Start Docker Build on CircleCi

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      start_at:
        description: 'Start the circleci workflow with base, cyng, crypto, node or dist'
        required: true
        default: 'node'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Start complete build
        shell: bash
        run: |
          echo '{"branch":"${{ steps.extract_branch.outputs.branch }}", "start_at":"${{ github.event.inputs.start_at }}"}'
          curl -u ${{secrets.GITHUB2CIRCLECITOKEN}}: -X POST https://circleci.com/api/v2/project/gh/mseemann/segw-build/pipeline --header "Content-Type: application/json" -d '{ "parameters": { "start_at":"${{ github.event.inputs.start_at }}"}}'
